# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/command.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14protos/command.proto\"\"\n\x07\x43ommand\x12\x17\n\x06opcode\x18\x01 \x01(\x0e\x32\x07.Opcode\"#\n\x08Response\x12\x17\n\x06opcode\x18\x01 \x01(\x0e\x32\x07.Opcode*(\n\x06Opcode\x12\n\n\x06UNUSED\x10\x00\x12\x08\n\x04PING\x10\x01\x12\x08\n\x04PONG\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.command_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_OPCODE']._serialized_start=97
  _globals['_OPCODE']._serialized_end=137
  _globals['_COMMAND']._serialized_start=24
  _globals['_COMMAND']._serialized_end=58
  _globals['_RESPONSE']._serialized_start=60
  _globals['_RESPONSE']._serialized_end=95
# @@protoc_insertion_point(module_scope)
